{{- range .Values.namespaces }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-all
  namespace: {{ . }}
spec:
  rules:
    - from:
        - source:
            ipBlocks:
              {{- range $.Values.ipBlocks }}
              - {{ . }}
              {{- end }}
{{- end }}
